// SPDX-License-Identifier: MIT
pragma solidity 0.8.33;

import {Test} from "forge-std/Test.sol";
import {Vault} from "../../src/core/Vault.sol";
import {StrategyManager} from "../../src/core/StrategyManager.sol";
import {AaveStrategy} from "../../src/strategies/AaveStrategy.sol";
import {CompoundStrategy} from "../../src/strategies/CompoundStrategy.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

/**
 * @title FuzzTest
 * @author cristianrisueo
 * @notice Stateless fuzz tests for the protocol
 * @dev Each test receives random inputs bounded to realistic ranges
 *      They are stateless: each execution starts from scratch after setUp()
 */
contract FuzzTest is Test {
    //* State variables

    /// @notice Protocol instances: Vault, manager and strategies
    Vault public vault;
    StrategyManager public manager;
    AaveStrategy public aave_strategy;
    CompoundStrategy public compound_strategy;

    /// @notice Contract addresses on Mainnet
    address constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
    address constant AAVE_POOL = 0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2;
    address constant COMPOUND_COMET = 0xA17581A9E3356d9A858b789D68B4d866e593aE94;
    address constant AAVE_REWARDS = 0x8164Cc65827dcFe994AB23944CBC90e0aa80bFcb;
    address constant COMPOUND_REWARDS = 0x1B0e765F6224C21223AeA2af16c1C46E38885a40;
    address constant AAVE_TOKEN = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;
    address constant COMP_TOKEN = 0xc00e94Cb662C3520282E6f5717214004A7f26888;
    address constant UNISWAP_ROUTER = 0xE592427A0AEce92De3Edee1F18E0157C05861564;
    uint24 constant POOL_FEE = 3000;

    /// @notice Test users
    address public alice = makeAddr("alice");
    address public founder;

    /// @notice Vault parameters
    uint256 constant MAX_TVL = 1000 ether;
    uint256 constant MIN_DEPOSIT = 0.01 ether;

    //* Testing environment setup

    /**
     * @notice Configures the testing environment
     * @dev Mainnet fork with full protocol deployed
     */
    function setUp() public {
        // Create a Mainnet fork using the Alchemy endpoint
        vm.createSelectFork(vm.envString("MAINNET_RPC_URL"));

        // Set the founder
        founder = makeAddr("founder");

        // Deploy and connect vault and manager
        manager = new StrategyManager(WETH);
        vault = new Vault(WETH, address(manager), address(this), founder);
        manager.initialize(address(vault));

        // Deploy strategies with real Mainnet addresses
        aave_strategy = new AaveStrategy(address(manager), AAVE_POOL, AAVE_REWARDS, WETH, AAVE_TOKEN, UNISWAP_ROUTER, POOL_FEE);
        compound_strategy = new CompoundStrategy(address(manager), COMPOUND_COMET, COMPOUND_REWARDS, WETH, COMP_TOKEN, UNISWAP_ROUTER, POOL_FEE);

        // Connect strategies to the manager
        manager.addStrategy(address(aave_strategy));
        manager.addStrategy(address(compound_strategy));
    }

    //* Internal helper functions

    /**
     * @notice Deposit helper
     * @param user User who deposits
     * @param amount Amount to deposit
     * @return shares Shares minted
     */
    function _deposit(address user, uint256 amount) internal returns (uint256 shares) {
        // Give the amount of WETH to the user and use their address
        deal(WETH, user, amount);
        vm.startPrank(user);

        // Approve the vault for the WETH transfer and deposit the amount into the vault
        IERC20(WETH).approve(address(vault), amount);
        shares = vault.deposit(amount, user);

        vm.stopPrank();
    }

    //* Stateless fuzz tests

    /**
     * @notice Fuzz: For any valid amount, deposit generates shares > 0 and totalAssets grows
     * @dev Bounds amount between MIN_DEPOSIT and MAX_TVL to avoid validation reverts
     * @param amount Random amount generated by the fuzzer
     */
    function testFuzz_Deposit_GeneratesShares(uint256 amount) public {
        // Bound the input to the vault's valid range
        amount = bound(amount, MIN_DEPOSIT, MAX_TVL);

        // Save totalAssets before the deposit
        uint256 total_before = vault.totalAssets();

        // Deposit and check that shares were generated
        uint256 shares = _deposit(alice, amount);
        assertGt(shares, 0, "Deposit should generate shares > 0");

        // Check that totalAssets grew (0.1% tolerance for protocol fees)
        assertApproxEqRel(vault.totalAssets(), total_before + amount, 0.001e18, "TotalAssets did not grow");
    }

    /**
     * @notice Fuzz: For any withdrawal, the user does not extract more than deposited
     * @dev Deposits amount, then withdraws a random percentage, always <= deposited
     * @param amount Random amount deposited
     * @param withdraw_pct Random percentage to withdraw (1-90%) of the deposit
     */
    function testFuzz_Withdraw_NeverExceedsDeposit(uint256 amount, uint256 withdraw_pct) public {
        // Bound inputs: valid amount, withdraw between 1% and 90% of the deposit
        amount = bound(amount, MIN_DEPOSIT, MAX_TVL);
        withdraw_pct = bound(withdraw_pct, 1, 90);

        // Deposit
        _deposit(alice, amount);

        // Calculate the net amount to withdraw (percentage of the deposit)
        uint256 withdraw_amount = (amount * withdraw_pct) / 100;
        if (withdraw_amount == 0) return;

        // Withdraw
        vm.prank(alice);
        vault.withdraw(withdraw_amount, alice, alice);

        // Check that what was received does not exceed what was deposited
        // This test seems a bit rigged to me (a 90% max leaves a very high buffer, and what if they receive 91%?)
        assertLe(IERC20(WETH).balanceOf(alice), amount, "User received more than deposited");
    }

    /**
     * @notice Fuzz: Redeem burns exactly the indicated shares
     * @dev For any amount of shares redeemed, the shares balance decreases by exactly that amount
     * @param amount Random amount deposited
     * @param redeem_pct Random percentage of shares to redeem
     */
    function testFuzz_Redeem_BurnsExactShares(uint256 amount, uint256 redeem_pct) public {
        // Bound inputs
        amount = bound(amount, MIN_DEPOSIT, MAX_TVL);
        redeem_pct = bound(redeem_pct, 1, 100);

        // Deposit and get shares
        uint256 shares = _deposit(alice, amount);

        // Calculate shares to redeem (between 1% and 100%)
        uint256 shares_to_redeem = (shares * redeem_pct) / 100;
        if (shares_to_redeem == 0) return;

        // Save shares balance before
        uint256 shares_before = vault.balanceOf(alice);

        // Redeem the calculated shares
        vm.prank(alice);
        vault.redeem(shares_to_redeem, alice, alice);

        // Check that exactly the indicated shares were burned
        uint256 shares_after = vault.balanceOf(alice);
        assertEq(shares_before - shares_after, shares_to_redeem, "The exact shares were not burned");
    }

    /**
     * @notice Fuzz: Deposit -> Immediate redeem never generates profit
     * @dev A user cannot profit by depositing and withdrawing immediately
     *      For any amount, assets_out <= amount (due to possible rounding loss)
     * @param amount Random amount deposited
     */
    function testFuzz_DepositRedeem_NeverProfitable(uint256 amount) public {
        // Bound to the protocol's valid range
        amount = bound(amount, MIN_DEPOSIT, MAX_TVL);

        // Deposit and redeem everything immediately
        uint256 shares = _deposit(alice, amount);

        vm.prank(alice);
        uint256 assets_out = vault.redeem(shares, alice, alice);

        // What was received never exceeds what was deposited (there may be rounding loss)
        assertLe(assets_out, amount, "Deposit-redeem should not be profitable");
    }
}
