// SPDX-License-Identifier: MIT
pragma solidity 0.8.33;

/**
 * @title IStrategy
 * @author cristianrisueo
 * @notice Standard interface that all strategies must implement
 * @dev Allows StrategyManager to treat strategies from different protocols:
 *      Aave, Compound, etc... In a uniform manner
 */
interface IStrategy {
    //* Events

    /**
     * @notice Emitted when assets are deposited into the strategy
     * @param caller Address that executed the deposit (should be strategy manager)
     * @param assets Amount of assets deposited
     * @param shares Shares received from the protocol where the deposit is made (corresponding xToken)
     */
    event Deposited(address indexed caller, uint256 assets, uint256 shares);

    /**
     * @notice Emitted when assets are withdrawn from the strategy
     * @param caller Address that executed the withdraw (should be strategy manager)
     * @param assets Amount of assets withdrawn
     * @param shares Shares burned by the protocol (xToken redeemed for asset)
     */
    event Withdrawn(address indexed caller, uint256 assets, uint256 shares);

    /**
     * @notice Emitted when the strategy's rewards are collected and reinvested
     * @param caller Address that executed the harvest (should be strategy manager)
     * @param profit Profit generated in asset after claiming and swapping rewards (the xTokens)
     */
    event Harvested(address indexed caller, uint256 profit);

    //* Main functions

    /**
     * @notice Deposits assets into the underlying protocol
     * @dev The caller must transfer assets to this strategy before calling. In a normal flow
     *      strategy manager transfers the assets to deposit to the corresponding strategy
     * @param assets Amount of assets to deposit
     * @return shares Shares received (the xTokens representing the deposit in protocol X)
     */
    function deposit(uint256 assets) external returns (uint256 shares);

    /**
     * @notice Withdraws assets from the underlying protocol
     * @dev Transfers assets to the caller after withdrawing, it's the reverse flow of deposit:
     *      The already converted assets go from the corresponding strategy to strategy manager
     * @param assets Amount of assets to withdraw
     * @return actual_withdrawn Assets actually withdrawn (amount to withdraw + generated yield)
     */
    function withdraw(uint256 assets) external returns (uint256 actual_withdrawn);

    /**
     * @notice Harvests rewards from the underlying protocol. Done continuously to maximize APY
     * @dev Claims rewards -> Swap to asset -> Re-invests in the protocol -> Increases APY even more
     * @dev Remember that rewards will come in xToken, they are an extra reward given by the underlying
     *      protocol for using it. To seek maximum APY, said reward is swapped and reinvested again
     * @return profit Profit in assets generated by rewards
     */
    function harvest() external returns (uint256 profit);

    //* Query functions

    /**
     * @notice Returns the total value of assets under management
     * @dev Includes deposited assets + accumulated yield
     * @dev Since the asset will be deposited in protocol X, it will be calculated
     *      using the shares (xToken) received from the underlying protocol
     * @return total Total value in assets (most likely in wei)
     */
    function totalAssets() external view returns (uint256 total);

    /**
     * @notice Returns the current APY of the underlying protocol
     * @dev In basis points: 100 = 1%, 350 = 3.5%, 1000 = 10%
     * @return apy_basis_points APY in basis points
     */
    function apy() external view returns (uint256 apy_basis_points);

    /**
     * @notice Returns the name of the strategy
     * @return strategy_name E.g.: "Aave v3 assets Strategy"
     */
    function name() external view returns (string memory strategy_name);

    /**
     * @notice Returns the address of the asset it manages
     * @return asset_address Address of the token used as underlying asset
     */
    function asset() external view returns (address asset_address);
}
